// design-system-foundation/packages/vue2/src/button.vue
<template>
  <button
    v-if="!loading"
    :style="componentStyles"
    :class="_classStringToObject(componentClasses)"
  >
    {{ text }}
  </button>
</template>

<script>
import "./button.css";
import { colors, darkColors, xmasColors, spacing } from "../../../foundations";

export default {
  name: "button",

  props: ["theme", "size", "type", "text"],

  data: () => ({ loading: true }),

  mounted() {
    this.loading = false;
  },

  computed: {
    componentClasses() {
      return `dsf-button flex flex-row justify-center items-center px-4 py-2 w-6 h-4 rounded`;
    },
    componentStyles() {
      const themeColors = {
        default: colors,
        dark: darkColors,
        xmas: xmasColors,
      };
      const themeColor = themeColors[this.theme] || themeColors.default;
      const types = {
        Primary: themeColor["color-primary"]["200"],
        Secondary: themeColor["color-secondary"]["200"],
      };
      const defaultType = types["Primary"];
      const sizes = {
        Small: {
          paddingTopBottom: spacing["1"],
          paddingLeftRight: spacing["2"],
        },
        Medium: {
          paddingTopBottom: spacing["2"],
          paddingLeftRight: spacing["3"],
        },
        Large: {
          paddingTopBottom: spacing["3"],
          paddingLeftRight: spacing["4"],
        },
      };
      const defaultSize = sizes["Medium"];
      const padding = `${
        sizes[this.size].paddingTopBottom || defaultSize.paddingTopBottom
      } ${sizes[this.size].paddingLeftRight || defaultSize.paddingLeftRight}`;
      return {
        backgroundColor: types[this.type] || defaultType,
        padding,
      };
    },
  },

  methods: {
    _classStringToObject(str) {
      const obj = {};
      if (typeof str !== "string") {
        return obj;
      }
      const classNames = str.trim().split(/\s+/);
      for (const name of classNames) {
        obj[name] = true;
      }
      return obj;
    },
  },
};
</script>

// design-system-foundation/packages/react/src/button.tsx
import * as React from "react";
import { useEffect } from "react";
import { useLocalObservable } from "mobx-react-lite";
type ButtonProps = {
  text: string;
  type: "Primary" | "Secondary";
  size: "Small" | "Medium" | "Large";
  theme: "dark" | "xmas";
};
import "./button.css";
import { colors, darkColors, xmasColors, spacing } from "../../../foundations";

export default function Button(props: ButtonProps) {
  const state = useLocalObservable(() => ({
    loading: true,
    get componentClasses() {
      return `dsf-button flex flex-row justify-center items-center px-4 py-2 w-6 h-4 rounded`;
    },
    get componentStyles() {
      const themeColors = {
        default: colors,
        dark: darkColors,
        xmas: xmasColors,
      };
      const themeColor = themeColors[props.theme] || themeColors.default;
      const types = {
        Primary: themeColor["color-primary"]["200"],
        Secondary: themeColor["color-secondary"]["200"],
      };
      const defaultType = types["Primary"];
      const sizes = {
        Small: {
          paddingTopBottom: spacing["1"],
          paddingLeftRight: spacing["2"],
        },
        Medium: {
          paddingTopBottom: spacing["2"],
          paddingLeftRight: spacing["3"],
        },
        Large: {
          paddingTopBottom: spacing["3"],
          paddingLeftRight: spacing["4"],
        },
      };
      const defaultSize = sizes["Medium"];
      const padding = `${
        sizes[props.size].paddingTopBottom || defaultSize.paddingTopBottom
      } ${sizes[props.size].paddingLeftRight || defaultSize.paddingLeftRight}`;
      return {
        backgroundColor: types[props.type] || defaultType,
        padding,
      };
    },
  }));

  useEffect(() => {
    state.loading = false;
  }, []);

  return (
    <>
      {!state.loading ? (
        <>
          <button
            style={state.componentStyles}
            className={state.componentClasses}
          >
            {props.text}
          </button>
        </>
      ) : null}
    </>
  );
}
