// vue/src/App.vue
<template>
  <app-button text="Button" type="Primary" size="Large" />
  <app-button text="Button" type="Secondary" size="Large" />
  <app-button text="Button" type="Primary" size="Medium" />
  <app-button text="Button" type="Secondary" size="Medium" />
  <app-button text="Button" type="Primary" size="Small" />
  <app-button text="Button" type="Secondary" size="Small" />
  <div class="text-color-secondary-400">Hello World</div>
</template>

<script setup>
import { Button as AppButton } from 'coral'
</script>

// react-app/src/App.js
import './App.css';
import AppButton from './components/button.tsx'

function App() {
  return (
    <div className="App">
     <AppButton text='Button' type="Primary" size="Large" theme="default" />
     <AppButton text='Button' type="Secondary" size="Large" theme="default" />
     <AppButton text='Button' type="Primary" size="Medium" theme="default" />
     <AppButton text='Button' type="Secondary" size="Medium" theme="default" />
     <AppButton text='Button' type="Primary" size="Small" theme="default" />
     <AppButton text='Button' type="Secondary" size="Small" theme="default" />
    </div>
  );
}

export default App;
